# Background and foreground colors
background = #050409
foreground = #F2EAF5

# Standard colors
palette = 0=#050409
palette = 1=#eb3d3f
palette = 2=#4dcf4d
palette = 3=#E5603D
palette = 4=#9190c6
palette = 5=#EBDAEA
palette = 6=#8ab0ea
palette = 7=#F2EAF5

# Bright colors
palette = 8=#6b6291
palette = 9=#f98b8d
palette = 10=#91e691
palette = 11=#f59f89
palette = 12=#bdbddf
palette = 13=#eedded
palette = 14=#b3cdf5
palette = 15=#eadcef
