# Background and foreground colors
background = #0f2138
foreground = #fdf4c4

# Standard colors
palette = 0=#0f2138
palette = 1=#c56363
palette = 2=#76c276
palette = 3=#cebd7c
palette = 4=#9a98be
palette = 5=#d095d0
palette = 6=#9fd5d5
palette = 7=#fdf4c4

# Bright colors
palette = 8=#7893b4
palette = 9=#e1a3a3
palette = 10=#b1dfb1
palette = 11=#e5dbb2
palette = 12=#c3c2da
palette = 13=#e5bee5
palette = 14=#c2e7e7
palette = 15=#fff7cc

background-opacity = 0.6
background-blur-radius = 10
